# Generated by Django 3.2.18 on 2023-04-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofiles_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='picture',
            field=models.ImageField(blank=True, default='img/favicon.ico', null=True, upload_to='img'),
        ),
    ]
